import "server-only";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";

/**
 * Where original BOQ files are kept.
 * - Production (Railway): an S3-compatible bucket, when S3_BUCKET is set.
 * - Local development: the web/.local-storage folder (git-ignored).
 * Files are private: the app reads them and streams them to signed-in admins.
 */
interface Storage {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  remove(key: string): Promise<void>;
}

const LOCAL_ROOT = path.resolve(process.cwd(), ".local-storage");

function localPath(key: string) {
  const full = path.resolve(LOCAL_ROOT, key);
  // Keys are generated by the app, but never let one escape the folder.
  if (!full.startsWith(LOCAL_ROOT + path.sep)) throw new Error("Invalid storage key");
  return full;
}

const local: Storage = {
  async put(key, body) {
    const file = localPath(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, body);
  },
  async get(key) {
    return readFile(localPath(key));
  },
  async remove(key) {
    await rm(localPath(key), { force: true });
  },
};

function s3Storage(bucket: string): Storage {
  const client = new S3Client({
    region: process.env.S3_REGION || "auto",
    endpoint: process.env.S3_ENDPOINT || undefined,
    forcePathStyle: Boolean(process.env.S3_ENDPOINT),
    credentials:
      process.env.S3_ACCESS_KEY_ID && process.env.S3_SECRET_ACCESS_KEY
        ? { accessKeyId: process.env.S3_ACCESS_KEY_ID, secretAccessKey: process.env.S3_SECRET_ACCESS_KEY }
        : undefined,
  });
  return {
    async put(key, body, contentType) {
      await client.send(new PutObjectCommand({ Bucket: bucket, Key: key, Body: body, ContentType: contentType }));
    },
    async get(key) {
      const res = await client.send(new GetObjectCommand({ Bucket: bucket, Key: key }));
      return Buffer.from(await res.Body!.transformToByteArray());
    },
    async remove(key) {
      await client.send(new DeleteObjectCommand({ Bucket: bucket, Key: key }));
    },
  };
}

export const storage: Storage = process.env.S3_BUCKET ? s3Storage(process.env.S3_BUCKET) : local;

/** Storage key for an uploaded BOQ: by content hash, so it's unique and never collides. */
export function boqFileKey(sha256: string, fileName: string) {
  const ext = path.extname(fileName).toLowerCase();
  return `boqs/${sha256.slice(0, 2)}/${sha256}${ext}`;
}
